/* tslint:disable */
/* eslint-disable */
/**
 * MayfieldGolfClub | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppSettingRequest,
  AppSettingResponse,
} from '../models/index';
import {
    AppSettingRequestFromJSON,
    AppSettingRequestToJSON,
    AppSettingResponseFromJSON,
    AppSettingResponseToJSON,
} from '../models/index';

export interface CreateAppSettingRequest {
    appSettingRequest: AppSettingRequest;
}

export interface DeleteAppSettingRequest {
    appSettingId: string;
}

export interface GetAppSettingRequest {
    appSettingId: string;
}

export interface GetAppSettingsRequest {
    names?: Array<string>;
}

export interface UpdateAppSettingRequest {
    appSettingId: string;
    appSettingRequest: AppSettingRequest;
}

/**
 * 
 */
export class AppSettingsApi extends runtime.BaseAPI {

    /**
     */
    async createAppSettingRaw(requestParameters: CreateAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppSettingResponse>> {
        if (requestParameters['appSettingRequest'] == null) {
            throw new runtime.RequiredError(
                'appSettingRequest',
                'Required parameter "appSettingRequest" was null or undefined when calling createAppSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/AppSettings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppSettingRequestToJSON(requestParameters['appSettingRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppSettingResponseFromJSON(jsonValue));
    }

    /**
     */
    async createAppSetting(requestParameters: CreateAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppSettingResponse> {
        const response = await this.createAppSettingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteAppSettingRaw(requestParameters: DeleteAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appSettingId'] == null) {
            throw new runtime.RequiredError(
                'appSettingId',
                'Required parameter "appSettingId" was null or undefined when calling deleteAppSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/AppSettings/{appSettingId}`;
        urlPath = urlPath.replace(`{${"appSettingId"}}`, encodeURIComponent(String(requestParameters['appSettingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteAppSetting(requestParameters: DeleteAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAppSettingRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAppSettingRaw(requestParameters: GetAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppSettingResponse>> {
        if (requestParameters['appSettingId'] == null) {
            throw new runtime.RequiredError(
                'appSettingId',
                'Required parameter "appSettingId" was null or undefined when calling getAppSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/AppSettings/{appSettingId}`;
        urlPath = urlPath.replace(`{${"appSettingId"}}`, encodeURIComponent(String(requestParameters['appSettingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppSettingResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAppSetting(requestParameters: GetAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppSettingResponse> {
        const response = await this.getAppSettingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSettingsRaw(requestParameters: GetAppSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppSettingResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['names'] != null) {
            queryParameters['names'] = requestParameters['names'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/AppSettings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppSettingResponseFromJSON));
    }

    /**
     */
    async getAppSettings(requestParameters: GetAppSettingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppSettingResponse>> {
        const response = await this.getAppSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateAppSettingRaw(requestParameters: UpdateAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['appSettingId'] == null) {
            throw new runtime.RequiredError(
                'appSettingId',
                'Required parameter "appSettingId" was null or undefined when calling updateAppSetting().'
            );
        }

        if (requestParameters['appSettingRequest'] == null) {
            throw new runtime.RequiredError(
                'appSettingRequest',
                'Required parameter "appSettingRequest" was null or undefined when calling updateAppSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/AppSettings/{appSettingId}`;
        urlPath = urlPath.replace(`{${"appSettingId"}}`, encodeURIComponent(String(requestParameters['appSettingId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AppSettingRequestToJSON(requestParameters['appSettingRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateAppSetting(requestParameters: UpdateAppSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateAppSettingRaw(requestParameters, initOverrides);
    }

}
