/* tslint:disable */
/* eslint-disable */
/**
 * MayfieldGolfClub | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSettingResponse
 */
export interface AppSettingResponse {
    /**
     * 
     * @type {string}
     * @memberof AppSettingResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AppSettingResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppSettingResponse
     */
    value: string;
}

/**
 * Check if a given object implements the AppSettingResponse interface.
 */
export function instanceOfAppSettingResponse(value: object): value is AppSettingResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AppSettingResponseFromJSON(json: any): AppSettingResponse {
    return AppSettingResponseFromJSONTyped(json, false);
}

export function AppSettingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSettingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'value': json['value'],
    };
}

export function AppSettingResponseToJSON(json: any): AppSettingResponse {
    return AppSettingResponseToJSONTyped(json, false);
}

export function AppSettingResponseToJSONTyped(value?: AppSettingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'value': value['value'],
    };
}

