/* tslint:disable */
/* eslint-disable */
/**
 * MayfieldGolfClub | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSettingRequest
 */
export interface AppSettingRequest {
    /**
     * 
     * @type {string}
     * @memberof AppSettingRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppSettingRequest
     */
    value: string;
}

/**
 * Check if a given object implements the AppSettingRequest interface.
 */
export function instanceOfAppSettingRequest(value: object): value is AppSettingRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AppSettingRequestFromJSON(json: any): AppSettingRequest {
    return AppSettingRequestFromJSONTyped(json, false);
}

export function AppSettingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSettingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function AppSettingRequestToJSON(json: any): AppSettingRequest {
    return AppSettingRequestToJSONTyped(json, false);
}

export function AppSettingRequestToJSONTyped(value?: AppSettingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

